### PR TITLE
FIX PR #98 -- advanced node taint querying

### LINKED ISSUE #91: Add support for node taints
It would be nice if we could add support for node taints. 
e.g. If a node has been cordoned and is set to no schedule/execute, it should be possible to exclude this.

e.g. 
```
kubectl get nodes
NAME
example-node-1    Ready,SchedulingDisabled   <none>          425d   v1.24.6
example-node-2    Ready                      <none>          227d   v1.24.6

kube-capacity

NODE              CPU REQUESTS    CPU LIMITS    MEMORY REQUESTS    MEMORY LIMITS
*                 560m (28%)      130m (7%)     572Mi (9%)         770Mi (13%)
example-node-1    220m (22%)      10m (1%)      192Mi (6%)         360Mi (12%)
example-node-2    340m (34%)      120m (12%)    380Mi (13%)        410Mi (14%)
```

Now if we exclude cordoned nodes:
```
kube-capacity --exclude-noschedule-nodes

NODE              CPU REQUESTS    CPU LIMITS    MEMORY REQUESTS    MEMORY LIMITS
*                 340m (34%)      132m (12%)    380Mi (13%)        410Mi (13%)
example-node-2    340m (34%)      120m (12%)    380Mi (13%)        10Mi (14%)
```

We can see have less capacity available than we thought.

### PR DESCRIPTION
**Pull request by isaacnboyd**
PR #98 required: 

* Rebasing #98 branch on main and resolving numerous conflicts, especially in the capacity tests (please review) 
* Cleaning lint (no return value on splitTaint() and goformatting)
* Testing new feature and adding instructions in README

resolves #91 
closes #98

### CODE REVIEW

File: pkg/capacity/capacity.go [hunk 1]
```diff
@@ -59,7 +60,103 @@ func FetchAndPrint(showContainers, showPods, showUtil, showPodCount, excludeTain
 	printList(&cm, showContainers, showPods, showUtil, showPodCount, showNamespace, output, sortBy, availableFormat)
 }
 
-func getPodsAndNodes(clientset kubernetes.Interface, excludeTainted bool, podLabels, nodeLabels, namespaceLabels, namespace string) (*corev1.PodList, *corev1.NodeList) {
+// Taints can have two possible formats, key1:effect or key1=value1:effect. This function handles both formats and returns each part as a separate string for comparison.
```
Comment (robscott) [inline pkg/capacity/capacity.go:63]: Nit: I'm used to function comments starting with the name of the function in golang, would recommend using that pattern throughout. Would also slightly prefer wrapping comment lines at 80 chars, but I don't think I've done great at following that here, it's just a common pattern in k8s projects.

File: README.md [hunk 2]
```diff
@@ -131,6 +131,27 @@ kube-capacity --namespace-labels team=api
 kube-capacity --node-labels kubernetes.io/role=node
 ```
 
+### Filtering By Taints
```
Comment (robscott) [inline README.md:134]: Thanks for adding docs to the readme, this is really great! One tiny suggestion would be to use "Node Taints" instead of just "Taints"
```suggestion
### Filtering By Node Taints
```

File: pkg/capacity/capacity.go [hunk 3]
```diff
@@ -59,7 +60,103 @@ func FetchAndPrint(showContainers, showPods, showUtil, showPodCount, excludeTain
...
+func splitTaint(taint string) (string, string, string) {
```
Comment (robscott) [inline pkg/capacity/capacity.go:64]: Can you use one of the the k8s helper functions instead here? Maybe something like this https://github.com/kubernetes/kubernetes/blob/a07b1aaa5b39b351ec8586de800baa5715304a3f/pkg/apis/core/helper/helpers.go#L428 or https://github.com/kubernetes/kubernetes/blob/a07b1aaa5b39b351ec8586de800baa5715304a3f/pkg/util/taints/taints.go#L91. I know those might not be quite a perfect fit, but maybe there's something along those lines that could help. Also in case it's ever helpful [cs.k8s.io](https://cs.k8s.io) is a k8s-wide codesearch that helps find if helper functions like this already exist - that's what I used here fwiw.

File: pkg/capacity/capacity.go [hunk 4]
```diff
@@ -143,10 +273,21 @@ func getPodMetrics(mClientset *metrics.Clientset, namespace string) *v1beta1.Pod
...
 
-func getNodeMetrics(mClientset *metrics.Clientset, nodeLabels string) *v1beta1.NodeMetricsList {
+func getNodeMetrics(mClientset *metrics.Clientset, nodeList *corev1.NodeList, nodeLabels string, nodeTaints string) *v1beta1.NodeMetricsList {
 	nmList, err := mClientset.MetricsV1beta1().NodeMetricses().List(context.TODO(), metav1.ListOptions{
 		LabelSelector: nodeLabels,
 	})
+
+	if nodeTaints != "" {
+		taintedNodeList := *nodeList
+		taintedNmList := removeNodeMetricsWithTaints(nmList, taintedNodeList)
```
Comment (robscott) [inline pkg/capacity/capacity.go:283]: Maybe a dumb question, but if we're just doing a join with the nodes later, and we're already removing the nodes that are tainted separately, do we need to actually remove the node metrics? I'd thought that might just automatically happen if corresponding nodes didn't exist, but it's been awhile since I've worked with this code.

**Review by robscott — COMMENTED** [review]
Thanks @isaacnboyd!

**Comment by robscott** [comment]
Hey @isaacnboyd, let me know if you think you'll have some time to work on this in the next week or so. Largely thanks to all your great improvements, I think it's probably close to time to cut another release (probably v0.8.0), but don't want this to miss the cut if you've got plans to work on it sometime soon.

**Comment by isaacnboyd** [comment]
> Hey @isaacnboyd, let me know if you think you'll have some time to work on this in the next week or so. Largely thanks to all your great improvements, I think it's probably close to time to cut another release (probably v0.8.0), but don't want this to miss the cut if you've got plans to work on it sometime soon.

Hey howdy Rob, yes I'd like to get this one into the release. I should be able to find some time to work on it here in the next few days.

File: pkg/capacity/capacity.go (hunk 4 above)
Comment (isaacnboyd) [reply pkg/capacity/capacity.go]: I believe you are correct. I tested `kube-capactiy -t` with and without this block of code and the results are the same.

File: pkg/capacity/capacity.go (hunk 3 above)
Comment (isaacnboyd) [reply pkg/capacity/capacity.go:62]: ooh cs.k8s.io is nifty! I'll have to do some digging there. 

Apparently you can create node taints that have no value. Like `kubectl taint nodes foo bar:NoSchedule`
as opposed to a k/v taint like `kubectl taint nodes foo dedicated=special-user:NoSchedule`. 
That's what this function is handling. Those 2 possible taint expressions.

I'll look around and see what's been built.

**Comment by robscott** [comment]
Thanks @isaacnboyd! Just let me know whenever it's ready for another round of review (or if it already is).

File: pkg/capacity/capacity.go (hunk 3 above)
Comment (isaacnboyd) [reply pkg/capacity/capacity.go:64]: I think you're right [`ParseTaints()` helper function](https://github.com/kubernetes/kubernetes/blob/a07b1aaa5b39b351ec8586de800baa5715304a3f/pkg/util/taints/taints.go#L91) can be a replacement for splitTaint(), it will change the user syntax from `kube-capacity --node-taints node.kubernetes.io/disk-pressure,!node.kubernetes.io/unschedulable:NoSchedule` to a more familiar syntax `kube-capacity --node-taints node.kubernetes.io/disk-pressure,node.kubernetes.io/unschedulable:NoSchedule-` with the `-` denoting removing a taint instead of `!`.

I think that's a valuable addition I'll try to get this added in the next few days.

Comment (isaacnboyd) [reply pkg/capacity/capacity.go]: splitTaint() has been replaced with k8s helper function ParseTaint(). See 903bc98321dc477a5961f2e2c3f275d49a3e3770

**Comment by isaacnboyd** [comment]
> Thanks @isaacnboyd! Just let me know whenever it's ready for another round of review (or if it already is).

Hey @robscott this is ready for another review.

**Comment by robscott** [comment]
Thanks @isaacnboyd!
